import type { NextPage } from 'next'
import Head from 'next/head'
import Map from '../components/Map';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map latitude={37.588194705681} longitude={127.03402453668} />
    </div>
  )
}

export default Home;
